consul:
    hostname: consul
    container_name: consul
    image: qnib/consul
    environment:
    - DC_NAME=dc1
    - RUN_SERVER=true
    - BOOTSTRAP_CONSUL=true
    ports:
    - "8500:8500"
    dns: 127.0.0.1

hbase:
    hostname: hbase
    container_name: hbase
    image: qnib/hbase
    environment:
    - DC_NAME=dc1
    - HADOOP_HDFS_NAMENODE=true
    links:
    - consul:consul
    ports:
    - 8042:8042 
    - 8088:8088
    - 50070:50070
    - 60000:60000
    - 60010:60010
    - 60030:60030
